require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'ChartApp' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # to enable hermes on iOS, change `false` to `true` and then install pods/var/folders/g6/1l44y_mx4mx5v42_kwjgrxy00000gn/T/com.apple.appstoreagent/simulator_screenshot_1A6E0EAB-5FA8-456B-BB15-9C8FFBF4F5F9.png
    :hermes_enabled => false
  )

  pod 'ReactNativeART', :path => '../node_modules/@react-native-community/art'

  target 'ChartAppTests' do
    inherit! :complete
    # Pods for testing
  end

  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable the next line.
  use_flipper!({ 'Flipper-Folly' => '2.5.3', 'Flipper' => '0.87.0', 'Flipper-RSocket' => '1.3.1' })

  post_install do |installer|
    react_native_post_install(installer)
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
